### ISSUE TITLE
Cannot select custom maps with custom mapinfo files.

### ISSUE THREAD

**Issue by matty45** [Assault-on-the-Control-Room/Opus#1]
I tried making a custom .map with its own mapinfo file as a test.
However it seems that opus has a weird issue while trying to select the map in its menu.

I made sure to make the maps id unique and use it for both the map and the mapinfo. 

Here is a video of the bug in action (Dont mind the mouse, strange quirk with the recording software):
https://streamable.com/dj03r

**Comment by HaydnTrigg** [comment]
This should be resolved as of 87fc4a17ebf5bcc2f21493243dfd39ea917872b4
